prism:
  dts_name: prism
  dts_path: /home/thiagodepaulo/exp/delta/data/prism

  prefix_columns: ["preference__", "english_proficiency__", "marital__", "education__", "employment__", "age__", "gender__"]

  train: 
    df_file: df_train.parquet
    text_file: texts_train.json
    emb_file: emb_train.npy

  dev:
    df_file: df_eval.parquet
    text_file: texts_eval.json
    emb_file: emb_eval.npy
  
  test:
    df_file: df_test_seen.parquet    
    text_file: texts_test_seen.json
    emb_file: emb_test_seen.npy

  test_unseen:
    df_file: df_test_unseen.parquet
    text_file: texts_test_unseen.json
    emb_file: emb_test_unseen.npy

psoup:
  dts_name: psoup
  dts_path: /home/thiagodepaulo/exp/delta/data/psoup

  vocab_file: vocab.txt

  prefix_columns: ["user_"]

  train:
    df_file: psoup_train_with_emb_uid_user_ohe.parquet
    text_file: texts_train.json
    emb_file: emb_train.npy  
    bow_file: bow_train.npz

  test:
    df_file: psoup_test_with_emb_uid_user_ohe.parquet   
    text_file: texts_test.json
    emb_file: emb_test.npy
    bow_file: bow_test.npz

simpler:
  dts_name: simpler
  dts_path: /home/thiagodepaulo/exp/delta/data/simpler  

  vocab_file: vocab.txt

  prefix_columns: ["user_"]

  train: 
    df_file: dataset_pairwise_preferences_train_with_emb_and_ohe.parquet
    text_file: texts_train.json
    emb_file: emb_train.npy
    bow_file: bow_train.npz

  dev:
    df_file: dataset_pairwise_preferences_dev_with_emb_and_ohe.parquet
    text_file: texts_dev.json
    emb_file: emb_dev.npy
    bow_file: bow_dev.npz

  test:
    df_file: dataset_pairwise_preferences_test_with_emb_and_ohe.parquet
    text_file: texts_test.json
    emb_file: emb_test.npy
    bow_file: bow_test.npz